#!/bin/sh
while read file
do
	case "$1" in
	"w")
		cp "$file" ~/Pictures/wallpapers/.selected_wallpaper.png &&
		feh --bg-fill "$HOME/Pictures/wallpapers/.selected_wallpaper.png" ;;
	"g")
		a="$file" &&
		path="${a%/*}" && 
		alacritty -e ranger $path &
		pid=$(pidof sxiv) &&
		kill $pid ;;
	esac
done
