#! /bin/sh

export sink="cat /home/josh/scripts/audio_out_module/audio"

#pgrep -x x11vnc > /dev/null || x11vnc -passwd notmyactualpass -forever &

pgrep -x flameshot > /dev/null || flameshot &

$HOME/.config/polybar/launch.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

bspc config border_width         5 
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a discord desktop='^10'
bspc rule -a Lutris desktop='^5'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a libreoffice desktop='^7'
bspc rule -a Thunar desktop='^6'
bspc rule -a Steam state=floating desktop='^9'
bspc rule -a sxiv state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

bspc config focused_border_color "#8ec07c"
bspc config normal_border_color "#282828"

# Mice bindings
#   Set mouse 1 to move floating windows
bspc config pointer_action1 move

#   Mouse 2 button resizes the window by side
bspc config pointer_action2 resize_side

#   Mouse 3 button (right mouse) resize by corner
bspc config pointer_action2 resize_corner
